### ISSUE TITLE
What is your model?

### ISSUE THREAD

**Issue by rain1024** [manhtai/vietseg#1]
Can you describe your network more details? How RNN can tokenize word?

**Comment by manhtai** [comment]
That is just a simple machine learning model. RNN is a kind of machine learning, isn't it?

**Comment by rain1024** [comment]
I don't really understand your workflow for word segmentation task. I took a look at your code but I don't understand how it works.

Can you describe your model with this simple input, output below

**Input**

`8 người nước ngoài nằm trong số 22 người chết do nổ bom tại Bangkok`

**Output**

`8` / `người` / `nước_ngoài` / `nằm` / `trong` / `số` / `22` / `người` / `chết` / `do` / `nổ bom` / `tại` / `Bangkok`

Thank you

PS: I really want to understand your works for contribution ^-^

**Comment by manhtai** [comment]
Machine learning means that you need a training set to train the model, so the workflow is you have a pre-trained input-output set, you use that to train the network, then you use the network to segment words in new sentences.

How can I describe it in more detail? :smile: 

My code is intended for illustration only so I think there is nothing to contribute anymore :smile_cat:
